version: '3.8'

services:
  # web service
  web:
    image: gdziewon/pixpursuit:latest
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --log-level debug
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - selenium-chrome

  # celery worker service
  worker_main:
    image: gdziewon/pixpursuit:latest
    command: celery -A app.celery worker --loglevel=info --queues=main_queue -P solo
    env_file:
      - .env
    depends_on:
      - redis
      - selenium-chrome

  # celery worker for beat tasks
  worker_beat:
    image: gdziewon/pixpursuit:latest
    command: celery -A app.celery worker --loglevel=info --queues=beat_queue -P solo
    env_file:
      - .env
    depends_on:
      - redis

  # celery beat service
  beat:
    image: gdziewon/pixpursuit:latest
    command: celery -A app.celery beat -l info
    env_file:
      - .env
    depends_on:
      - redis

    # redis service
  redis:
    image: "redis:alpine"

    # nginx service
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/api.pixpursuit.rocks/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/api.pixpursuit.rocks/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - web

  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    privileged: true
    shm_size: 2g
    volumes:
      - /dev/shm:/dev/shm

volumes:
  redis-data:
