name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'PixPursuit_backend/**'

jobs:
  # build-and-test:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: PixPursuit_backend

  #   steps:
  #   - uses: actions/checkout@v2

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.9'

    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    # - name: Run tests
    #   run: pytest
    #   env:
    #     AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
    #     MONGODB_URI: ${{ secrets.MONGODB_URI }}
    #     DO_SPACE_ENDPOINT: ${{ secrets.DO_SPACE_ENDPOINT }}
    #     DO_SPACE_ACCESS_KEY: ${{ secrets.DO_SPACE_ACCESS_KEY }}
    #     DO_SPACE_SECRET_KEY: ${{ secrets.DO_SPACE_SECRET_KEY }}
    #     DO_SPACE_BUCKET: ${{ secrets.DO_SPACE_BUCKET }}
    #     NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
    #     NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
    #     MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
    #     MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    #     MAIL_APP_PASSWORD: ${{ secrets.MAIL_APP_PASSWORD }}
    #     TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
    #     TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    #     TEST_EMAIL: ${{ secrets.TEST_EMAIL }}

  deploy:
    # needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        working-directory: PixPursuit_backend

    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        docker build -t gdziewon/pixpursuit:latest .
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login --username gdziewon --password-stdin
        docker push gdziewon/pixpursuit:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /root/pixpursuit/PixPursuit_backend
          docker-compose pull
          docker-compose up -d --force-recreate
